### ISSUE TITLE
Dad joke

### ISSUE THREAD

**Issue by Eva774** [nerdland-unofficial-fans/nerdlandbot_js#9]
Replicate the functionality of the Python bot

**Comment by DrSkunk** [comment]
Relevant url in Python bot: https://github.com/nerdland-unofficial-fans/nerdlandbot/blob/d15ab88bc469afe6f43955d8231a5848bfb2693c/nerdlandbot/commands/random.py#L120

I'll try to do this one as a first contribution

**Comment by DrSkunk** [comment]
Done in #76
